from typing import List

from src.domain import Order

from mitsuki.data import CrudRepository


@CrudRepository(entity=Order)
class OrderRepository:
    """
    Repository for Order entities.

    Base CRUD methods are generated by @CrudRepository. Query DSL methods are
    declared as stubs and implemented from their names.
    """

    async def find_by_user_id(self, user_id: int) -> List[Order]: ...
