from src.domain import User

from mitsuki.data import CrudRepository


@CrudRepository(entity=User)
class UserRepository:
    """
    Repository for User entities.

    Base CRUD methods are generated by @CrudRepository, and are instrumented
    like any other component method when @Instrumented is on the application.
    """
